apiVersion: velero.io/v1
kind: Restore
metadata:
  namespace: openshift-adp
  name: restore-1
spec:
  backupName: backup-1
  includeNamespaces:
        - wordpress
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  restorePVs: true
